title: Jason Brown
logo: "/jason.png?raw=true" 
description: > # your text below (remove <br> elements if you don't need line breaks)
 Python/Intelligent Automation Engineer
  <br><br>

  <a href="mailto:jasondexterbrown@gmail.com">jasondexterbrown@gmail.com</a>
  <br>
  
  <a href="https://www.linkedin.com/in/jasondexterbrown/">LinkedIn Profile</a>
  <br><br>
  <h2 style="font-size:10"><strong><i>Python Projects</i></strong></h2>
 
  <br>
  <a href="https://github.com/JdexterBrown/Money_Man-of-Wall-Street.git">Money Man Project</a>
  <br>
 <a href="https://github.com/JdexterBrown/jason_d_brown_automation_profile.github.io">Jason Brown Developer Github Page Project</a>
  
  
theme: jekyll-theme-minimal
